name: Qt

on: [push, pull_request]

jobs:
  build-windows:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install Qt
      uses: jurplel/install-qt-action@d325aaf2a8baeeda41ad0b5d39f84a6af9bcf005 # v4.3.0
      with:
        cache: true

    - name: Visual Studio command prompt
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
      with:
        arch: x64

    - name: Build
      run: |
        mkdir build && cd build
        qmake ../src/${{ github.event.repository.name }}.pro
        nmake
        cd release
        Remove-Item *.obj, *.res, *.cpp, *.h
        windeployqt.exe --no-compiler-runtime ${{ github.event.repository.name }}.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-windows
        path: build/release/*

    - name: Get lowercase OS name
      id: osname
      uses: ASzc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # v6
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        string: ${{ runner.os }}

    - name: Compress artifacts
      uses: vimtor/action-zip@1379ea20d4c5705669ba81fd626dd01b1c738f26 # v1.2
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        files: build/release/
        dest: ${{ github.event.repository.name }}-${{ steps.osname.outputs.lowercase }}.zip

    - name: Release
      uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
        files: ${{ github.event.repository.name }}-${{ steps.osname.outputs.lowercase }}.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-nix:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install Nix
      uses: cachix/install-nix-action@7be5dee1421f63d07e71ce6e0a9f8a4b07c2a487 # v31.6.1

    - name: Build
      run: |
        nix build
        nix bundle --bundler github:ralismark/nix-appimage .

